QUOTES_IMG = (
      "https://i.imgur.com/ycHGQDn.jpg", 
      "https://i.imgur.com/YkqT3iw.jpg", 
      "https://i.imgur.com/aBgfzRa.jpg", 
      "https://i.imgur.com/47rmohR.jpg", 
      "https://i.imgur.com/eh2t6Dj.jpg", 
      "https://i.imgur.com/RitAy08.jpg", 
      "https://i.imgur.com/RYQoTge.jpg", 
      "https://i.imgur.com/JWbOdnC.jpg", 
      "https://i.imgur.com/h2cwx8k.jpg", 
      "https://i.imgur.com/Inc9fFc.jpg", 
      "https://i.imgur.com/zdXOZKq.jpg", 
      "https://i.imgur.com/E5VjFSn.jpg", 
      "https://i.imgur.com/TQaUREY.jpg", 
      "https://i.imgur.com/oFkevp3.jpg", 
      "https://i.imgur.com/3crEQmb.jpg", 
      "https://i.imgur.com/0YazmEy.jpg", 
      "https://i.imgur.com/wkj0mQU.jpg", 
      "https://i.imgur.com/AcxLYCm.jpg", 
      "https://i.imgur.com/jw6Att0.jpg",
      "https://i.imgur.com/1xytUXa.jpg",
      "https://imgur.com/a/pjhouAJ.jpg",
      "https://imgur.com/a/Rj5y2hN.jpg"
      
      )
